---
watch:
  - .trmnlp.yml
  - src

custom_fields:
  api_key_id: "{{ env.TRADING212_API_KEY_ID }}"
  api_secret: "{{ env.TRADING212_API_SECRET }}"
  account_type: live

variables:
  trmnl:
    plugin_settings:
      instance_name: My Portfolio
